version: '3.7'

services:
  node:
    container_name: node_server
    image: nnvgm/example-node-mongo
    networks:
      - common
    environment:
      PORT: 3000
      MONGO_URL: 'mongodb://mongo/example'
      NODE_ENV: 'production'

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - common

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - common

networks:
  common:
